### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by zhenduow** [truthless11/GDPL#5]
Hi Ryuichi,

I am very interested in your GDPL work. I tried to follow the instructions to run you code. When I run the pretraining experiment, I get the following CUDA out of memory error right after all the the last epoch :

```
DEBUG:root:<<dialog policy>> test, epoch 31, loss_a:0.0605404159987504
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
INFO:root:Loading goal model is done
DEBUG:root:start loading irl train
DEBUG:root:finish loading irl train
DEBUG:root:start loading irl valid
DEBUG:root:finish loading irl valid
DEBUG:root:start loading irl test
DEBUG:root:finish loading irl test
INFO:root:<<dialog policy>> loaded checkpoint from file: model_agenda/best_ppo.val.mdl
INFO:root:<<dialog policy>> loaded checkpoint from file: model_agenda/best_ppo.pol.mdl
illegal value: dont care, slot: type domain: hotel
illegal value: dont care, slot: area domain: attraction
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/zhenduow/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 119, in rebuild_cuda_tensor
    event_sync_required)
RuntimeError: CUDA error: out of memory
```

I am using a GeForce RTX 2080 with 4 cores and 11Gi each. I am not sure if it is enough... Can you share the gpu information you use to run the experiments?

Also I tried these methods but none of them worked, do you have any suggestions?
1. Reduce the batchsize argument.
2. Specify GPU using CUDA_VISIBLE_DEVICES=...

Thank you very much!

Best,
Zhenduo

**Comment by truthless11** [comment]
I used a single TITAN X GPU for training. Maybe you can turn down the parameter `--process`.
